### ISSUE TITLE
Use with PropertyWebScraper

### ISSUE THREAD

**Issue by etewiah** [mbejda/single-property-real-estate-website#1]
This is awesome, thanks for making it open source!!

Hope you don't mind me using it for a project I'm doing which allows you to scrape real estate data from websites.  I wanted to be able to display the data in a decent single property page but couldn't find a nice one available so I put together my own:

https://real-estate-web-scraper.herokuapp.com/single_property_view?url=https%3A%2F%2Fwww.realtor.com%2Frealestateandhomes-detail%2F1804-Pontiac-Dr_Alamogordo_NM_88310_M17581-40846

I much prefer your's so I'd like to use it instead.

**Comment by mbejda** [comment]
Go for it, just give me a link back somewhere to my blog. Its responsive, well documented and you can easily change theme colors on it.

**Comment by etewiah** [comment]
Great, thanks.  I'll make sure to link back to you.
